theme: jekyll-theme-dinky
title: Open Source GIScience
description: Joseph Holler's Open Source GIScience Resources at Middlebury College
collections:
  lessons:
    output: true
timezone: America/New_York
